name: pray_together
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  curved_navigation_bar: ^0.3.7
  flutter_svg: ^0.21.0+1
  flutter_signin_button: ^2.0.0
  dartz: ^0.9.2
  custom_navigator: ^0.3.0
  flutter_compass: ^0.6.0
  flutter_qiblah: ^2.0.0
  permission_handler: ^6.1.3
  kosher_dart: ^2.0.1
  syncfusion_flutter_calendar: ^19.1.63
  get: ^4.1.4
  http: ^0.13.3
  awesome_dialog: ^2.0.0

  # Open Pdf file:
  syncfusion_flutter_pdfviewer: ^19.1.56-beta

  # state managment:
  provider: ^5.0.0
  
  # user authentication:
  firebase_auth: ^1.1.0
  firebase_core: ^1.0.3
  google_sign_in: ^5.0.0

  # user in DB:
  cloud_firestore: ^1.0.5
  cloud_functions: ^1.0.3

  # Access to GPS with app:
  geolocator: ^7.0.3
  geoflutterfire: ^3.0.0-nullsafety.2

  # Nevigate with Waze and GoogleMaps:
  ##map_launcher: ^2.0.0

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - lib/core/assets/logo.png
    - lib/compass/core/compass.png
    - lib/siddurim/core/imag_siddur.png
    - lib/core/assets/Tample3.png
    - lib/synagoguesprofile/core/imag_home.png
  
    ## Pdfs:
    - lib/siddurim/core/pdf/Askenaz_Arvit.pdf
    - lib/siddurim/core/pdf/Askenaz_Mincha.pdf
    - lib/siddurim/core/pdf/Askenaz_Shaharit.pdf
    - lib/siddurim/core/pdf/Edot_Arvit.pdf
    - lib/siddurim/core/pdf/Edot_Mincha.pdf
    - lib/siddurim/core/pdf/Edot_Shaharit.pdf
    - lib/siddurim/core/pdf/Sefard_Arvit.pdf
    - lib/siddurim/core/pdf/Sefard_Mincha.pdf
    - lib/siddurim/core/pdf/Sefard_Shaharit.pdf
    - lib/siddurim/core/pdf/Kriat Hatorah.pdf

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Guttman
      fonts:
        - asset: lib/core/fonts/STAM.ttf
          weight: 700
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
